config/routes.rb
HotelAdvisor::Application.routes.draw do
  namespace :api do
    namespace :v1, defaults: {format: 'json'} do
      resources :hotels do
        resources :reviews
      end
      resources :reviews
      resources :users
    end
  end

  devise_for :users
  resources :users

  resources :hotels do
    resources :reviews
  end
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  root 'hotels#index'
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :room_description,  presence: true, length: {minimum: 5, maximum: 1000};
  validates :price_of_room, presence: true, numericality: {greater_than: 0}
  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :count_name, :street, :state, :city, presence: true, length: {minimum: 3, maximum: 100}

  def self.top_hotels
    Hotel.all.where('rating >= ?',4).limit(5)
  end
end

app/controllers/api/v1/hotels_controller.rb
class Api::V1::HotelsController < ApplicationController

  respond_to :json

  def index
    respond_with Hotel.all
  end

  def new
    respond_with Hotel.new
  end

  def show
    if !Hotel.where(params[:id]).exists?
      redirect_to root_path
      flash[:notice] = 'Error find id'
    else
      respond_with Hotel.find(params[:id])
    end
  end

  def edit
    respond_with Hotel.find(params[:id])
  end

  def create
    hotel = Hotel.new(hotel_params)
    if hotel.save
      render json: hotel, status: 201, location: [:api, hotel]
    else
      render 'edit'
    end
  end

  def update
    binding.pry
    hotel = Hotel.find(params[:id])

    if hotel.update(hotel_params)
      render json: hotel, status: 200, location: [:api, hotel]
    else
      render json: {errors: hotel.errors}, status: 422
    end
  end

  def destroy
    hotel = Hotel.find(params[:id])
    hotel.destroy
    head 204
  end

  private

  def hotel_params
    params.require(:hotel).permit(:title, :image, :breakfast, :price_of_room, :rating, :city, :street, :state, :count_name, :room_description)
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :find_hotel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @hotels = Hotel.page(params[:page]).per(3)
    # @top_hotels = Hotel.all.where('rating > ?', 2).limit(5)
  end

  def new
    @hotel = current_user.hotels.build
  end

  def show
    if @hotel.reviews.blank?
      @average_review = 0
    else
      @average_review = @hotel.reviews.average(:rating)
      @hotel.rating = @average_review
      @hotel.save
    end
  end

  def create
    @hotel = current_user.hotels.build(hotel_params)

    if @hotel.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @hotel.update(hotel_params)
      redirect_to hotel_path(@hotel)
    else
      render 'edit'
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    redirect_to root_path
  end

  private

  def hotel_params
    params.require(:hotel).permit( :title, :image, :breakfast, :price_of_room, :rating, :city, :street, :state, :count_name, :room_description)
  end


  def find_hotel
    @hotel = Hotel.find(params[:id])
  end


end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.haml
.addhotelform
  = simple_form_for @hotel, :html => {:multipart => true} do |f|
    .Hoteltitleform
      = f.input :title,                         label: 'Hotel Title'
    = f.input :image,           as: :file,    label: 'Hotel Image'
    .roompriceform
      = f.input :price_of_room,                 label: 'Room Price'
    .stateform
      = f.input :state,                         label: 'State'
    .countryform
      = f.input :count_name,                    label: 'Country'
    .cityform
      = f.input :city,                          label: 'City'
    .streetform
      = f.input :street,                        label: 'Street'
    = f.input :breakfast,       as: :boolean, label: 'Include breakfast'
    .hdesform
      = f.input :room_description,              label: 'Hotel Description'
    = f.button :submit

app/views/hotels/edit.html.haml
%link{ :rel => 'stylesheet', :href => 'http://yui.yahooapis.com/pure/0.6.0/pure-min.css'}

%h1 Edit hotel

= render 'form'

app/views/hotels/index.html.haml
.container
  %h1 Top Hotels
  - Hotel.top_hotels.each do |hotel|
    .row.col-md-2
      .hotellistitem
        .thumbnail
          %img{:alt => "", :src => hotel.image_url.to_s, :style => 'height: 300px'}
        %h1 #{hotel.title}
        .average-review-rating{'data-score' => hotel.rating}
        %p #{hotel.room_description}
.hotelslist
  %h1{:align => 'center'} Hotels
  .container
    .row
      - if Hotel.count == 0
        %h1 There is no hotels
      - else
        - @hotels.each do |hotel|
          .col-md-4
            .hotellistitem
              .thumbnail
                %img{:alt => "", :src => hotel.image_url.to_s, :style => 'height: 300px'}
              %h2 #{hotel.title}
              .average-review-rating{'data-score' => hotel.rating}
              %p.text-justify #{hotel.room_description}
              .btn-blue
                %a{:href => hotel_path(hotel)} Details
%center
  = paginate @hotels
:javascript
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
:javascript
  $('.average-review-rating').raty({
  	readOnly: true,
  	path: '/assets/',
  	score: function() {
  		return $(this).attr('data-score')
  	}
  });

app/views/hotels/new.html.haml
.container
  %h1 New hotel

  = render 'form'

app/views/hotels/show.html.haml
.container
  .row
    .hotel-title
      %h1 #{@hotel.title}
      .row
        .average-review-rating{'data-score' => @average_review}
      %p
        %b #{@hotel.count_name}, #{@hotel.state}, #{@hotel.city}, #{@hotel.street}
  .row
    .hotview
      .row
        = image_tag @hotel.image_url.to_s, width: '250'
        .marg.thumbnail
          .descript
            %h3 Описание:
            %p #{@hotel.room_description}

  .row
    %p Отзывы:
    = render @hotel.reviews
    - if user_signed_in?
      - if @hotel.user_id == current_user.id || current_user.admin?
        %p= link_to 'Add review', new_hotel_review_path(@hotel)
        = link_to "Edit Hotel", edit_hotel_path(@hotel)
        = link_to "Delete Hotel", hotel_path(@hotel), method: :delete, data: { confirm: "Are you sure?" }
        %p= link_to 'Back', root_path
:javascript
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
:javascript
  $('.average-review-rating').raty({
  	readOnly: true,
  	path: '/assets/',
  	score: function() {
  		return $(this).attr('data-score')
  	}
  });