config/routes.rb
HotelAdvisor::Application.routes.draw do
  namespace :api do
    namespace :v1, defaults: {format: 'json'} do
      resources :hotels do
        resources :reviews
      end
      resources :reviews
      resources :users
    end
  end

  devise_for :users
  resources :users

  resources :hotels do
    resources :reviews
  end
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  root 'hotels#index'
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
  before_action :authenticate_with_token!

  respond_to :json

  def new
    respond_with Review.new
  end

  def show
    if !Review.where(params[:id]).exists?
      redirect_to root_path
      flash[:notice] = 'Error find id'
    else
      respond_with Review.find(params[:id])
    end
  end

  def edit
    respond_with Review.find(params[:id])
  end

  def index
    respond_with Review.all
  end

  def create
    review = Review.new(user_params)
    if user.save
      render json: review, status: 201, location: [:api, review]
    else
      render json: {errors: review.errors}, status: 422
    end
  end

  def update
    review = Review.find(params[:id])

    if review.update(user_params)
      render json: review, status: 200, location: [:api, review]
    else
      render 'edit'
      render json: {errors: review.errors}, status: 422
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    head 204
  end

  private

  def review_params
    params.require(:reviews).permit(:rating, :comment)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_hotel
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.hotel_id = @hotel.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to hotel_path(@hotel)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to hotel_path(@hotel)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to hotel_path(@hotel)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end


  def find_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
.container
  = simple_form_for ([@hotel, @hotel.reviews.build]) do |f|
    #rating-form
      %label Rating
    = f.input :comment
    = f.button :submit

:javascript
   $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
   });

app/views/reviews/_review.html.haml
.container-hotel.review-rating{'data-score' => review.rating}
%p= review.comment
- if user_signed_in?
  - if review.user_id == current_user.id || current_user.admin?
    = link_to 'Edit review', edit_hotel_review_path(review.hotel, review)
    = link_to 'Delete review', hotel_review_path(review.hotel, review), method: :delete, data: {confirm: 'Are yo u sure?'}

app/views/reviews/edit.html.haml
.container
  %h1 Edit Review
  = simple_form_for ([@hotel, @review]) do |f|
    #rating-form
      %label Rating
    = f.input :comment
    = f.button :submit

  :javascript
    $('#rating-form').raty({
      path: '/assets/',
      scoreName: 'review[rating]'
    });

app/views/reviews/new.html.haml
.container
  %h1 New Review

  = render 'form'

  %p= link_to 'Back', root_path