config/routes.rb
HotelAdvisor::Application.routes.draw do
  namespace :api do
    namespace :v1, defaults: {format: 'json'} do
      resources :hotels do
        resources :reviews
      end
      resources :reviews
      resources :users
    end
  end

  devise_for :users
  resources :users

  resources :hotels do
    resources :reviews
  end
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  root 'hotels#index'
end

app/views/layouts/_footer.html.haml
.footer
  %ul.pull-left
    %li
      %a{:href => "#"} Terms
    %li
      %a{:href => "#"} Contacts
    %li
      %a{:href => "#"} Confidentiality
  %p.pull-right © 2015 Hotel Advisor. All rights reserved

app/views/layouts/_header.html.haml
%body
  .main-navigation
    .pull-right
      %ul
        - if user_signed_in?
          %li
            = link_to 'Sing Out', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Log In', new_user_session_path
        - if user_signed_in?
          %li
            = link_to 'Profile', current_user
          %li
            = link_to 'Add Hotel', new_hotel_path
        - else
          %li
            = link_to 'Sing Up', new_user_registration_path
        %li
          = link_to 'About Us', about_path
        %li
          = link_to 'Contact Us', contact_path
        %li
          = link_to 'Help', help_path
        %li
          = link_to 'Home', root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TestHotel
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
  %p.alert.alert-info
    = notice
  %p.alert.alert-morning
    = alert

    = yield
  = render 'layouts/footer'